spring:
  config:
    import: aws-parameterstore:/cloud-intro-team-app/prod/
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  team:
    name: ${TEAM_NAME}